# Change these first
owner: gedesco-git # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: AC COM
    url: $SITE_AC_COM
  - name: ADA ES
    url: $SITE_ADA_ES
  #- name: AD ES
  #  url: $SITE_AD_ES
  - name: BC ES
    url: $SITE_BC_ES
  - name: CRF COM
    url: $SITE_CRF_COM
  - name: DIS ES
    url: $SITE_DIS_ES
  - name: EC3 COM
    url: $SITE_EC3_COM
  # - name: EPAG ES
  # url: $SITE_EP_ES
  - name: FDC ES
    url: $SITE_FDC_ES
  - name: GDCH ES 
    url: $SITE_GDCH_ES
  - name: GDCLB ES
    url: $SITE_GDCLB_ES
  # - name: GDCSA ES
  # url: $SITE_GDCSA_ES
  - name: COM GURU
    url: $SITE_COM_GURU 
  - name: GDC ES
    url: $SITE_GDC_ES
  - name: MDF ES
    url: $SITE_MDF_ES
  - name: PGR COM
    url: $SITE_PGR_COM
  - name: PRS ES
    url: $SITE_PRS_ES
  - name: RCB ES
    url: $SITE_RCB_ES
  - name: URG COM
    url: $SITE_URG_COM
  - name: VZOO COM
    url: $SITE_VZOO_COM

assignees:
  - gedesco-git

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GDC Uptime
  introTitle: "**GDC Uptime** is powered by [Upptime](https://github.com/upptime/upptime) and GitHub."
  introMessage: Statuses use **real-time** data
  navbar:
    - title: Status
      href: /uptime
